### ISSUE TITLE
Doesn't compile on kernel 5.19

### ISSUE THREAD

**Issue by ghost** [hexdump0815/rtl8723cs#1]
Hi,

After upgrading to kernel 5.19, the rtl8723cs can't be compiled
```
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c: In function ‘cfg80211_rtw_scan’:
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:2522:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 2522 |                 struct cfg80211_scan_info info;
      |                 ^~~~~~
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c: At top level:
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:6890:20: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, unsigned int)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *)’ [-Werror=incompatible-pointer-types]
 6890 |         .stop_ap = cfg80211_rtw_stop_ap,
      |                    ^~~~~~~~~~~~~~~~~~~~
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:6890:20: note: (near initialization for ‘rtw_cfg80211_ops.stop_ap’)
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_wdev_unregister’:
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:7121:17: error: ‘struct wireless_dev’ has no member named ‘current_bss’
 7121 |         if (wdev->current_bss) {
      |                 ^~
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c: In function ‘cfg80211_rtw_change_iface’:
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:1843:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1843 |                 is_p2p = _TRUE;
/usr/src/realtek-rtl8723cs-0.0~git20210902.0fb0c24/os_dep/linux/ioctl_cfg80211.c:1845:9: note: here
 1845 |         case NL80211_IFTYPE_STATION:
      |         ^~~~
```

Any fix soon ?

**Comment by hexdump0815** [comment]
@jJit0 - please have a look here: https://github.com/hexdump0815/linux-mainline-and-mali-rockchip-rk33xx-kernel/tree/master/misc.rkc/patches - there are patches to compile with v5.19.2+ and v6.0 ...

**Comment by ghost** [comment]
I tried the patch, but still not building. I got other errors this time.

**Comment by hexdump0815** [comment]
@jJit0 -what errors? you only used the rtl8723cs patch for your kernel version (and ignored all other patches in that dir) - right? (at least this way it was ment to be done in this case)

**Comment by ghost** [comment]
I pulled the whole repo and compiled the driver.
I think the error is due to the arch, the driver patch is for an arm board.

I compared both my old driver source with the one u gave me. It's incompatible for X86_64

**Comment by hexdump0815** [comment]
@jJit0 - oh that could be - i'm only compiling, using and testing it on arm

**Comment by ghost** [comment]
Ok that's why then
